### ISSUE TITLE
Investigate for hot reloading

### ISSUE THREAD

**Issue by Nargonath** [Nargonath/cra-build-watch#17]
Hot reloading is lost because I had to remove webpack dev server from CRA configuration in order to write the project files to the disk hence losing hot reloading feature. Let's see if there is a way to bring it back either through special mode with WDS or with a custom method.

**Comment by apanizo** [comment]
Hi @Nargonath first of all, thank you for creating this library. Is really useful.

I am not too sure about my availability but if you give me some guidance I would be happy to investigate the hot reloading as well, and maybe submit a PR. 

Right now when I apply some changes I need to open and close the chrome extension and is not really cool.

Thanks!!

**Comment by Nargonath** [comment]
Hey @apanizo! I'm glad this tool is useful to you, thanks for letting me know.

Actually now I think something can be done, perhaps we can even reintroduce `webpack-dev-server` because in one of the latest release they introduce an option to write on the disk instead of the memory. https://webpack.js.org/configuration/dev-server/#devserverwritetodisk-

IIRC `create-react-app` has also been updated with the version of WDS required to use that option. You would need to check their changelog to be sure though. If that's the case, we can try keeping WDS in the config, tweek the webpack configuration by adding that option and see how it goes.

Feel free to ping me if you need some more help or explanations. Thanks for your help. 👍

**Comment by apanizo** [comment]
I have taken a look, and yes, the `writeToDisk` option is available on `create-react-app`.  If you take a look into the [changelog](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md#213-january-4-2019), WDS was updated to 3.1.14, and the `writeToDisk` option was released in 3.1.10.

So after playing a bit with it, I am missing some points here 😅 

When I run `yarn watch` everything seems to be fine, but if I open the extension I get this error:
```
Uncaught SyntaxError: The URL 'chrome-extension:beoefdfgfpliobcablom/sockjs-node' is invalid
    at new SockJS (main.js:70)
    at eval (webpackHotDevClient.js:53)
    at Object.../../node_modules/react-scripts/node_modules/react-dev-utils/webpackHotDevClient.js (0.chunk.js:1825)
    at __webpack_require__ (bundle.js:782)
    at fn (bundle.js:150)
    at Object.0 (main.chunk.js:113)
    at __webpack_require__ (bundle.js:782)
    at checkDeferredModules (bundle.js:46)
    at Array.webpackJsonpCallback [as push] (bundle.js:33)
    at main.chunk.js:1
__get-internal-source?fileName=webpack-internal%3A%2F%2F%2F..%2F..%2Fnode_modules%2Fsockjs-client%2Flib%2Fmain.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
__get-internal-source?fileName=webpack-internal%3A%2F%2F%2F..%2F..%2Fnode_modules%2Freact-scripts%2Fnode_modules%2Freact-dev-utils%2FwebpackHotDevClient.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

@Nargonath can you guess something?

**Comment by bjankord** [comment]
I've been able to get a live-reload functionality working with my express app that uses create-react-app and wanted to share. It is not the same as HMR, but it does enough to help improve the developer experience for me.

Add chokidar to watch for file changes in the src directory and socket.io to emit "files changed" event
```js
const socket = require('socket.io');
const chokidar = require('chokidar');

// Setup server
const port = '8080';
const server = app.listen(port, () => {
  console.log(`Server is running on: ${port}`);
});

// Setup file watcher to emit event to the client on './src' file changes
// Used to live-reload the web page
let io = socket(server)
io.on('connection', socket => {
  const buildDir = path.join(__dirname, '..', 'src');
  const watcher = chokidar.watch(buildDir);

  const watchHandler = () => {
    socket.emit("files changed");
  };

  watcher.on('ready', () => {
    watcher.on('add', watchHandler);
    watcher.on('change', watchHandler);
  });

  socket.on('disconnect', () => {
    watcher.close();
  });
});
```

And then in your client code, you need to listen for this "files changed" event and reload the current page.
Create a file named `reload.js` in your public directory and add the following.
```js
// Open a connection.
var socket = io('http://localhost:8080');

// Listen for the event.
socket.on("files changed", function () {
  // delay to allow cra to build files before we reload
  setTimeout(window.location.reload.bind(window.location), 250);
});
```
Then in your index.html, add the following:

```ejs
<% if(process.env.NODE_ENV !== 'production'){ %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>
    <script src="reload.js"></script>
<% } %>
```

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
