### ISSUE TITLE
Create CSS file

### ISSUE THREAD

**Issue by sguillia** [Nargonath/cra-build-watch#186]
Hi

With `react-scripts build`, the `asset-manifest.json` contains these lines among others:

```
{
  "files": {
    "main.css": "./static/css/main.d626b3da.chunk.css",
    "main.js": "./static/js/main.22ef37af.chunk.js"
  }
}
```

With `cra-build-watch`, the `asset-manifest.json` contains these lines:

```
{
  "files": {
    "main.js": "/js/bundle.js",
    "main.js.map": "/js/bundle.js.map",
    "index.html": "/index.html"
  },
  "entrypoints": [
    "js/bundle.js"
  ]
}
```

_main.css_ is missing

Is it possible to generate _main.css_ with cra-build-watch?

**Comment by EugenMayer** [comment]
Same issue here, main.css is missing which is mandatory of course. Any chance to add this or at least a hint?

**Comment by tasmith039** [comment]
@Nargonath I also have a need for this. I also have some bandwidth to make a PR for it if you could give a little direction how it might be pulled off...

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
