### ISSUE TITLE
Issue with main.chunk.js build on every other save?

### ISSUE THREAD

**Issue by danrday** [Nargonath/cra-build-watch#207]
This library is great, thank you!

I have an issue where I'm serving up my React dev build from a Phoenix server. It's working fine, but only on every other save in my React project. I found that every time I save a change,
the last line in my build/js/main.chunk.js alternates from

```javascript
},[[0,"runtime-main",0]]]);
```

to 

```javascript
},[[0,"runtime-main",1]]]);
```

Phoenix serves up everything when it's 0, but not when it's 1. Does anyone know what this code is doing and whether it might be possible to have it return 0 always? I've tried looking at webpack docs but having trouble understanding what is going on here.
Thank you for any ideas!
-Dan

**Comment by danrday** [comment]
It looks like webpack alternates between saving and loading 0.chunk.js and 1.chunk.js on every other save, guessing to ensure the browser re-loads the new changes instead of caching? Anyway solved this by loading both chunks in my main file.

```
 <script src="../react-dev-build/js/0.chunk.js"></script>
  <script src="../react-dev-build/js/1.chunk.js"></script>
```

**Comment by Nargonath** [comment]
Alright, glad you could figure out something for your problem. Sorry I don't have much time for open-source lately.
