### ISSUE TITLE
For some reason it works on every other save

### ISSUE THREAD

**Issue by bbgvalayev** [Nargonath/cra-build-watch#221]
When I make a code change, i see ✔ Start webpack watch but then we reload the page its blank, then i have to save again and it fixes.

**Comment by Nargonath** [comment]
Hum that's weird. Are you using `cra-build-watch` as is or do you use any of its arguments?

**Comment by danrday** [comment]
Does this help? https://github.com/Nargonath/cra-build-watch/issues/207

Make sure you are loading both js files, it alternates which file it writes to on every save: 
 <script src="../react-dev-build/js/0.chunk.js"></script>
  <script src="../react-dev-build/js/1.chunk.js"></script>

**Comment by bbgvalayev** [comment]
i use it without args, ill check if both bundles are loaded

**Comment by bbgvalayev** [comment]
Ok, i was loading the file outside of the express route. Now, in development, it will be read every time from build dir so that it picks up the changing `1/0.chunk.js`.

**Comment by Nargonath** [comment]
Looks like you figured it. I'll close this for now but feel free to comment if that's not the case.
