### ISSUE TITLE
Can I be notified when CRA rebuilds?

### ISSUE THREAD

**Issue by joaovbibiano** [Nargonath/cra-build-watch#232]
I want to be notified to implement something to reload the page, with socket or something, getting the behavier as we have on normal "npm start".

I need the dev bundle, to be served by others application.

**Comment by Nargonath** [comment]
I think this is what you're looking for: https://github.com/Nargonath/cra-build-watch/pull/218. I'll close this for now, feel free to tell me if that's not the case.

**Comment by joaovbibiano** [comment]
> I think this is what you're looking for: #218. I'll close this for now, feel free to tell me if that's not the case.

Yes it is, thank you
