### ISSUE TITLE
Add parameter to skip initial cleanup

### ISSUE THREAD

**Issue by umutcanbolat** [Nargonath/cra-build-watch#250]
Hello!

First of all thanks for this tool. It's helpful.

I would like to add the possibility to skip the initial cleanup by introducing `--skip-cleanup` param. 

When I do the cleanup and copy some files into the build folder by another watch script before running `cra-build-watch`, I would like to be able to skip the cleanup made by `cra-build-watch`.

PR will follow this issue.
Thanks.

**Comment by Nargonath** [comment]
I'm glad to see that this tool is providing value to you. That's a good suggestion, thanks. I'll try to look at it when I get some time. There are other people waiting for their stuff to get some movement too so I might not tackle this first. Just to be transparent. 😉

**Comment by umutcanbolat** [comment]
Good to hear something back. Take your time, and feel free to leave some comments when you are available.
Best!

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
