### ISSUE TITLE
cannot find react-scripts/config/paths when running on cra 3.4.1

### ISSUE THREAD

**Issue by EugenMayer** [Nargonath/cra-build-watch#253]
running `cra-build-watch` i get

```
> cra-build-watch

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'react-scripts/config/paths'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
```

running it using `cra-build-watch --react-scripts-version=3.4.1` did not work either. any suggestions?

**Comment by EugenMayer** [comment]
Found the reason, we are repackaging cra with very small adjustments under `@kw/react-scripts` this the folder is `node_modules/@kw/react-scripts` and not `node_modules/react-scripts` - creating a symlink fixes this issue.

is this desired or could we make this lookup a little more dynamic?

**Comment by Nargonath** [comment]
Initially this package was intended to be used primarly with the bare `react-scripts` module. However many people use CRA with other tools that allow them to customize its config, as you seem to do also. If you have an elegant solution in mind, feel free to spin up a PR so we can discuss it further.

To be honest, I didn't expect the project to gain the traction it did and thought it would have been replaced by a native CRA feature by now but it doesn't seem to be priority as of now.

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
