### ISSUE TITLE
Watch multiple applications

### ISSUE THREAD

**Issue by dariusrosendahl** [Nargonath/cra-build-watch#27]
Hi!

We're using webpack to create react applications to incoroprate it into existing applications so your plugins sounds perfect.

We're creating multiple applications like this:

```
entry: {
  app1: paths.app1,
  app2: paths.app2
```

How do I watch these? Right now I'm getting the following error

```
⠋ Update webpack configuration/paths/webpack/node_modules/cra-build-watch/scripts/index.js:46
config.entry = config.entry.filter(fileName => !fileName.match(/webpackHotDevClient/));

TypeError: config.entry.filter is not a function
```

**Comment by Nargonath** [comment]
Hi!

I'm glad you considered using my plugin but it is meant to be used in `create-react-app` projects as it is tweaking `react-scripts` webpack configuration. I could be mistaking but that's not your case, is it?

**Comment by dariusrosendahl** [comment]
We are using the ```create-react-app```. Have have ejected and tweaked the build and config to enable multiple entries. Like I showed in my previous post.

**Comment by Nargonath** [comment]
My bad, I see. I don't have an answer right now, I'll have to think about it.

**Comment by AudereSemper** [comment]
hello, i'm in the same situation, do you find some idea/solution during this months ?

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
