### ISSUE TITLE
Not working with react-scripts@4.0.0-next.98

### ISSUE THREAD

**Issue by Haaxor1689** [Nargonath/cra-build-watch#274]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): Yes
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 15.2.1
* *module version with issue*: 3.4.0
* *last module version without issue*: -
* *environment* (e.g. node, browser, native): browser
* *used with* (e.g. hapi application, another framework, standalone, ...): -
* *any other relevant information*: react-scripts@4.0.0-next.98

#### What are you trying to achieve or the steps to reproduce?

The `cra-build-watch` ends with error if I'm using `react-scripts@4.0.0-next.98` which I need to use because of emotion and new jsx pragma system in react 17.

#### What was the result you got?

The error:

```
yarn run v1.22.5
$ cra-build-watch

- Update webpack configurationC:\Projects\_InQool\jch2\web\node_modules\cra-build-watch\scripts\index.js:98
  config.module.rules[oneOfIndex].oneOf[0].options.name = `media/[name].[hash:8].[ext]`;
                                       ^

TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (C:\Projects\_InQool\jch2\web\node_modules\cra-build-watch\scripts\index.js:98:40)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

#### What result did you expect?

No error.

**Comment by MatissJanis** [comment]
+1

CRA v4 is not working with this tool.

**Comment by norcino** [comment]
Same issue with react script 5

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
