### ISSUE TITLE
"--after-rebuild-hook" runs before "--after-initial-build-hook"

### ISSUE THREAD

**Issue by alesniak303** [Nargonath/cra-build-watch#282]
* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: v14.0.0
* *module version with issue*: 6.3.0 
* *last module version without issue*: unknown 
* *environment* (e.g. node, browser, native):  macOS BigSur
* *used with* (e.g. hapi application, another framework, standalone, ...): CRA
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

I added the initial and rebuild hooks as follows:

```js
  "scripts": {
      "hotbuild": "cra-build-watch -v -b webapp/myapp --after-initial-build-hook 'config/inital.sh -d webapp/myapp -w web.xml' --after-rebuild-hook 'config/rebuild.sh",
     ...
 }
```

#### What was the result you got?
```text
✔ after rebuild hook: Rebuild complete. [OK]

✔ after initial build hook: Initial build. Complete. [OK]
```

#### What result did you expect?
On the initial build, I should only see the "after initial build hook" and should never see the "after rebuild hook".  
On subsequent builds,  I should only see the "after rebuild hook".

**Comment by bytrangle** [comment]
> #### What was the result you got?
> ```
> ✔ after rebuild hook: Rebuild complete. [OK]
> 
> ✔ after initial build hook: Initial build. Complete. [OK]
> ```
> 
> #### What result did you expect?
> On the initial build, I should only see the "after initial build hook" and should never see the "after rebuild hook".
> On subsequent builds, I should only see the "after rebuild hook".

I'm getting the same output as you: after rebuild hook is console.log before after initial build hook. But does your script still work in the sequence you expect i.e. `config/rebuild.sh is run after `config/initial/sh`?  It's only the shell feedback is is out of order, correct?

**Comment by alesniak303** [comment]
It didn’t actually occur to me to check.

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
