### ISSUE TITLE
%PUBLIC_URL% is not affected by --public-path

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Nargonath/cra-build-watch#296]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.13.1
* *module version with issue*: v3.4.0
* *last module version without issue*: none
* *environment* (e.g. node, browser, native): browser
* *used with* (e.g. hapi application, another framework, standalone, ...): just cra
* *any other relevant information*: -

#### What are you trying to achieve or the steps to reproduce?

I need all references (js, css, favicon etc.) to be relative to the current folder, not to root as it's by default.
For production build (`npm run build`), I can `"homepage": "./"` to package.json.
It would be nice if cra-build-watch would pick up this parameter as well, but I found a workaround almost as good:
using `cra-build-watch --public-path ./`.
Unfortunately, while js and css references are relative, `%PUBLIC_URL%` is not replaced with `./`, so I get:

#### What was the result you got?

```
<link rel="icon" href="/favicon.ico" />
...
<script src="./js/bundle.js">
```

For favicon defined just as in the default cra:
`<link rel="icon" href="%PUBLIC_URL%/favicon.ico" />`

#### What result did you expect?

```
<link rel="icon" href="./favicon.ico" />
...
<script src="./js/bundle.js">
```

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
