### ISSUE TITLE
[Feature Request] Create a dev build without a watcher

### ISSUE THREAD

**Issue by devxpy** [Nargonath/cra-build-watch#3]
__Why I need this:__
I want to be able to create a single build for each time django renders a template.
A file watcher has to be started and maintained throughout the course of the django server's lifetime. On the other hand, we can just do a build each time django renders a template, since its development. This will also ensure any files that might have been missed by the file watcher.

API suggestion
`cra-build-watch --no-watch`

I'm a python guy and have a limited knowledge of webpack. However, I am ready to help if you can point me in the right direction.

Thanks/

**Comment by Nargonath** [comment]
I'm not sure I fully understand what you want to achieve but unfortunately I won't have the time this week to look into it in depth. I'll come back at it later on when my schedule allows it.

**Comment by devxpy** [comment]
Nvm, I figured it out myself..

https://github.com/pycampers/react-pages/blob/master/nodejs/config/webpack.config.dev.js

**Comment by Nargonath** [comment]
Alright, glad you found a solution to your problem. Good job. :+1:

**Comment by Nargonath** [comment]
Cool! 😄
