### ISSUE TITLE
TypeError: x.trim is not a function

### ISSUE THREAD

**Issue by RomanKornev** [Nargonath/cra-build-watch#304]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: v15.9.0
* *module version with issue*: 3.4.0
* *last module version without issue*: unknown
* *environment* (e.g. node, browser, native): WSL2 Ubuntu
* *used with* (e.g. hapi application, another framework, standalone, ...): react
* *any other relevant information*: -

#### What are you trying to achieve or the steps to reproduce?

I'm trying to `npm run watch`

#### What was the result you got?
❯ npm run watch

> ts_sandbox@0.1.0 watch
> cra-build-watch

/home/df/work/ts_sandbox/node_modules/camelcase/index.js:35
                        .map(x => x.trim())
                                    ^

TypeError: x.trim is not a function
    at /home/df/work/ts_sandbox/node_modules/camelcase/index.js:35:16
    at Array.map (<anonymous>)
    at module.exports (/home/df/work/ts_sandbox/node_modules/camelcase/index.js:35:5)
    at /home/df/work/ts_sandbox/node_modules/camelcase-keys/index.js:55:17
    at mapObject (/home/df/work/ts_sandbox/node_modules/map-obj/index.js:34:28)
    at module.exports (/home/df/work/ts_sandbox/node_modules/map-obj/index.js:53:9)
    at camelCaseConvert (/home/df/work/ts_sandbox/node_modules/camelcase-keys/index.js:68:9)
    at module.exports (/home/df/work/ts_sandbox/node_modules/camelcase-keys/index.js:76:9)
    at meow (/home/df/work/ts_sandbox/node_modules/meow/index.js:180:16)
    at Object.<anonymous> (/home/df/work/ts_sandbox/node_modules/cra-build-watch/utils/cliHandler.js:5:18)
npm ERR! code 1
npm ERR! path /home/df/work/ts_sandbox
npm ERR! command failed
npm ERR! command sh -c cra-build-watch

#### What result did you expect?
Successfull run

**Comment by Nargonath** [comment]
Thanks @RomanKornev for raising this issue. I just released a new beta `4.0.0-beta.1` which is a complete rewrite. You can find more information here: https://github.com/Nargonath/cra-build-watch/releases/tag/v4.0.0-beta.1 and in the README: https://github.com/Nargonath/cra-build-watch/tree/v4.0.0-beta.1#notes-for-version-v400-beta-testers. Would you mind giving it a shot to see if it fixes your issue?

**Comment by bytrangle** [comment]
@Nargonath I will find time to test the beta later, but just a quick ask? Does it handle build hooks?

**Comment by Nargonath** [comment]
@bytrangle In this first draft, all the features were removed just to rely on `webpackDevServer` `writeOnDisk` feature and see how it goes. I'm not sure I'll be able to keep the build hooks if we go that route. I'd have to dig more through it.

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
