### ISSUE TITLE
application does not work with pathes in the URL with react BrowserRouter on initial invocation 

### ISSUE THREAD

**Issue by wollo** [Nargonath/cra-build-watch#325]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 14.15
* *module version*: 
* *environment* (e.g. node, browser, native): browser
* *used with* (e.g. hapi application, another framework, standalone, ...): react BrowserRouter
* *any other relevant information*:

#### What problem are you trying to solve?

I am using your great tool in a CI environment to build a dev version of my app. I let the watcher run and rerminate it with the completed hook to get a build in my build directory. This is then served afterwards by gitlab pages or standalone by an ngings server.
This is working so far great. I have only an issue with pathes. When I access the application served on root path via nginx 
like https://subdomain.mydomain.com its works fine and also the routes in teh application are resolved, as they should.
But when I invoke the application with one of this routed pathes like https://subdomain.mydomain.com/show/UIDV4
the page is not displayed. In fact no code is loaded.
But the  application works fine in the same configuration, when I use the usal production build, or when I start it under node with npm react-scripts start

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
