### ISSUE TITLE
Not compatible with react-scripts v5

### ISSUE THREAD

**Issue by jagannathBhat** [Nargonath/cra-build-watch#368]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 16.5.0
* *module version with issue*: 3.4.0
* *last module version without issue*: unknown
* *environment* (e.g. node, browser, native): macOS 12.1
* *used with* (e.g. hapi application, another framework, standalone, ...): react
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

Add a script to package.json:

```json
{
  "scripts": {
    "watch": "cra-build-watch"
  }
}
```

Run the command

```sh
yarn watch
```

#### What was the result you got?

Got the following error

```sh
 config.module.rules[oneOfIndex].oneOf[0].options.name = `media/[name].[hash:8].[ext]`;
                                                        ^
                                                        
TypeError: Cannot set property 'name' of undefined
```

#### What result did you expect?

No Error

**Comment by mscoobby** [comment]
When can we have this one fixed? I have just upgraded react-scripts to v5 on our projects and now the watch is not working.

**Comment by pateketu** [comment]
same here, would like to use this but cannot because I am using v5

**Comment by Nargonath** [comment]
My bandwidth is very limited right now so I don't have much time to dedicate to this project. I don't have any ETA for this.

**Comment by jagannathBhat** [comment]
@mscoobby @pateketu Try this [package](https://www.npmjs.com/package/@jagannathbhat/cra-build-watch) for now. Published it from my fork.

**Comment by pateketu** [comment]
thanks @jagannathBhat  this works great -:)

**Comment by phal0r** [comment]
@jagannathBhat Your fork loads webpack4, but cra5 uses webpack5, so there are validation errors for the configuration

**Comment by Nargonath** [comment]
Sorry everybody but I don't have time to maintain this project anymore. I'll archive it so it's clear to everybody that they should fork it if they want to improve it.
