### ISSUE TITLE
Missing dependency on html-webpack-plugin

### ISSUE THREAD

**Issue by kamsar** [Nargonath/cra-build-watch#4]
I gave this a try just now, and it complained that it couldn't find the `html-webpack-plugin` module.

Maybe a missing dependency/peerdependency?

**Comment by Nargonath** [comment]
Yeah I think you are right. I thought I could rely on `html-webpack-plugin` being installed because IIRC `react-scripts` depends on it but that was a bad call. If they decide to remove it then it would not work. I'll correct that. Thank you for reporting this.
