### ISSUE TITLE
Typescript build errors output?

### ISSUE THREAD

**Issue by bryceg** [Nargonath/cra-build-watch#81]
Is it possible to get the build errors output for typescript projects?

**Comment by Nargonath** [comment]
I must admit I never tested it with Typescript as I'm not using it but my first guess would be that it can be done. I'd have to look into it because as of now I have no clue how they handle it. Feel free to have a try at it if you want.

**Comment by Nargonath** [comment]
Do you have or could you make an example setup I could play with?

**Comment by Etchelon** [comment]
> Do you have or could you make an example setup I could play with?

Hi, and thanks for this script. I'm just getting started with React and coming from Angular's CLI, not having a watch option for the build is annoying, so I searched and found your package, very helpful!

I could do a repro it but it's just enough to take the following steps:

1. `npx create-react-app my-app --template typescript && cd my-app`
2. `npm i -D cra-build-watch`
3. open 2 terminals and run npm run start in one, npm run watch in the other
4. open App.tsx and add number as return type for the App function (see screenshot)

I will see your script triggering recompilation, with no errors; the official react-script start does tell me there's an error:
![image](https://user-images.githubusercontent.com/4141889/94144212-285a7d80-fe71-11ea-8ea1-958bd1e2e3ad.png)

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
