### ISSUE TITLE
3.0.0 stuck on "Clear destination folder"

### ISSUE THREAD

**Issue by NZainchkovskiy** [Nargonath/cra-build-watch#83]
I'm using CRA application with react-scripts version 3.2.0.
cra-build-watch version 3.0.0.
When I execute npm run watch it do "Update webpack configuration" and "Clear destination folder" steps and then just do nothing. build folder is empty after running watch.
What I doing wrong?
Thank you!
![image](https://user-images.githubusercontent.com/19357901/66822400-d9ac2000-ef4c-11e9-9136-5f0332e3233e.png)

**Comment by NZainchkovskiy** [comment]
Update - I'm dowgraded to 2.0.1 and now it's working. So it's some issue with new version maybe.

**Comment by Nargonath** [comment]
Alright, there seems to be a regression with `3.0.0` indeed. I'll have a look at it, thanks.

**Comment by Nargonath** [comment]
Hum I just did a test on a brand new `create-react-app` project with the code on `master` branch and also on the `v3.0.0` tag but everything worked well for me. I wonder if the problem does not come from Windows.

**Comment by NZainchkovskiy** [comment]
I did the same test just now (brand new create-react-app) and it still stucks.
Different computers, windows only.
I can't test on linux now, but on windows 3.0.0 seems to be broken. Version 2.0.1 works just fine.

**Comment by Nargonath** [comment]
Thanks for your test.

I tested on OSX 10.14.6 on my part it works fine. I don't develop at all on Windows.

**Comment by NZainchkovskiy** [comment]
Maybe I can troubleshoot it somehow?
I think many developers with windows platforms has interest in your library.
I'm ready to provide any help for solving this issue, if you could give me some directions.

**Comment by Nargonath** [comment]
Thanks for your help, it is appreciated. 👍 

I have to take some time and think this through so I can give you clear guidelines.

**Comment by Nargonath** [comment]
The `v3.0.0` was mostly about upgrading dependencies so there

**Comment by Nargonath** [comment]
First I have a question for you, which version of `node` are you using?

Second, the `v3.0.0` was mostly about upgrading dependencies hence the problem might come from one of them. You can find the list of the commits here: https://github.com/Nargonath/cra-build-watch/compare/v2.0.1...v3.0.0. What you could be doing to debug this is:
* fork the repo
* checkout the `v2.0.1` tag
* setup a fresh project of `create-react-app`
* [link](https://docs.npmjs.com/cli/link.html) your local `cra-build-watch` fork to your fresh CRA project
* setup the `watch` script as you would if you had installed `cra-build-watch` within your CRA project
* run `npm outdated` in your local fork to get the list of all the outdated dependencies
* upgrade one
* run the `watch` script in your CRA project
* notice if the problem still appears or not
* if not then proceed to the next outdated dependency and so on until you find a culprit

What do you think?

**Comment by annakhloyan** [comment]
> I'm using CRA application with react-scripts version 3.2.0.
> cra-build-watch version 3.0.0.
> When I execute npm run watch it do "Update webpack configuration" and "Clear destination folder" steps and then just do nothing. build folder is empty after running watch.
> What I doing wrong?
> Thank you!
> ![image](https://user-images.githubusercontent.com/19357901/66822400-d9ac2000-ef4c-11e9-9136-5f0332e3233e.png)



> I did the same test just now (brand new create-react-app) and it still stucks.
> Different computers, windows only.
> I can't test on linux now, but on windows 3.0.0 seems to be broken. Version 2.0.1 works just fine.

Have the same issue.
using 12.13.03 v of node.
Version 2.0.1 still not working

**Comment by Nargonath** [comment]
Thanks @annakhloyan for sharing. Currently I don't have the free time to really dig into this and I'm also not on Windows. I don't have a define solution for you as `2.0.1` does not work in your case. Does a plain CRA project works on `node@12.13.03` on your setup?

**Comment by TJYSunset** [comment]
Having this issue too. I'm also on Windows (10 version 18362.418). 2.0.1 worked while 3.0 didn't work on a almost brand new typescript react project created with cra (just configured eslint, prettier & stylelint).

software | version
--- | ---
node | 13.1.0
create-react-app/react-scripts | 3.2.0
react | 16.12.0
typescript | 3.7.2

Sorry but I didn't have time to test it without typescript.

**Comment by wpdevteam** [comment]
Having the same issue as well on Windows 10. 2.0.1 worked while 3.0 didn't. 3.0 works fine on Linux (Ubuntu).

**Comment by Nargonath** [comment]
@wpdevteam thanks glad to hear it works on Linux. This definitely seems to be a problem with Windows. I wonder whether it comes from a TypeScript setup, are you using it with TS?

**Comment by JokerDan** [comment]
Hi guys.
3.0.0 was working fine for me on my work laptop (OSX).

At home I dev on windows and ran in to the same issues reported above.
(`Win 10 v1909 BUILD 18363.535`)

Tried with node version `v10.16.3` and node version `v13.6.0`.

I **am not** using Typescript for my project, but appreaciate that react-scripts transpiles to TS iirc.

```
  "dependencies": {
    "@material-ui/core": "^4.5.0",
    "@material-ui/icons": "^4.4.3",
    "@octokit/rest": "^16.31.0",
    "express": "^4.17.1",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-scripts": "^3.2.0"
  },
  "devDependencies": {
    "cra-build-watch": "^3.0.0"
  }
```

Downgrading to v2.0.1 worked for me too.

**Comment by JokerDan** [comment]
@Nargonath I hope you don't mind, I have opened a PR above. It appears to have resolved the issue for me on Windows and the script still works for me on OSX. I don't have a machine with a flavour of linux on at the moment to test Ubuntu or similar.

Some details in the PR and feel free to @ me for anything else.

**Comment by Nargonath** [comment]
Good initiative @JokerDan . Glad you managed to find a solution. I'll try to take a look at it this weekend.
