### ISSUE TITLE
PUBLIC_URL isn't replaced in index.html

### ISSUE THREAD

**Issue by andreisoare** [Nargonath/cra-build-watch#9]
After the build using this tool, I still see `<link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">` in index.html. Is there a way to easily fix this?

**Comment by Nargonath** [comment]
Thanks for raising the issue. I'd have to look into it to have an answer for you.

**Comment by Nargonath** [comment]
I found the problem. They changed the position of the HtmlWebpackPlugin in their plugins array and it was replacing the InterpolationPlugin so you didn't have access to environment variable in your index.html anymore. I'm working on a PR and should be probably done by tonight.

**Comment by Nargonath** [comment]
I've underestimated this issue, even with the above fix it does not work. I'll have to dig deeper into this.
