### ISSUE TITLE
Use this on non-ejected project?

### ISSUE THREAD

**Issue by Noam-Bendelac** [Nargonath/cra-build-watch#96]
Sorry if I missed this in the README, but I'd like to know if I can use cra-build-watch on my project if I haven't run eject. I'd rather not lose the functionality of CRA scripts so I don't want to eject but cra-build-watch sounds like exactly what I need.

Edit -- Could someone label this as a question? I believe I can't do it on my end

**Comment by Nargonath** [comment]
Yes that's exactly the purpose of this tool. I didn't want to have to eject either which led me to develop this.

It is not directly mentioned in the README, I'll add something about it. Thanks for the feedback and I'm glad it will be useful to you.
