### ISSUE TITLE
Add proper tests

### ISSUE THREAD

**Issue by Nargonath** [Nargonath/cra-build-watch#98]
I had a discussion on `hapi` slack about that, here are some resources that can help:

- https://github.com/hapipal/hpal/blob/master/test/run-util.js#L9-L41
- https://github.com/hapipal/hpal/blob/master/test/index.js#L1590-L1604
- https://github.com/hapipal/hpal/tree/master/test/closet/run-list-commands
- https://github.com/felixheck/laabr/blob/master/test/_helpers.js#L21-L35

Here a screenshots of the actual conversation:
![image](https://user-images.githubusercontent.com/583657/69953883-77a67a80-14fa-11ea-9366-e5a0ead3dfe1.png)

**Comment by Nargonath** [comment]
One thing to take a look at could be the `c8` project too.

**Comment by thejuicer32** [comment]
> I had a discussion on `hapi` slack about that, here are some resources that can help:
> 
> * https://github.com/hapipal/hpal/blob/master/test/run-util.js#L9-L41
> * https://github.com/hapipal/hpal/blob/master/test/index.js#L1590-L1604
> * https://github.com/hapipal/hpal/tree/master/test/closet/run-list-commands
> * https://github.com/felixheck/laabr/blob/master/test/_helpers.js#L21-L35
> 
> Here a screenshots of the actual conversation:
> ![image](https://user-images.githubusercontent.com/583657/69953883-77a67a80-14fa-11ea-9366-e5a0ead3dfe1.png)

**Comment by Nargonath** [comment]
Sorry I don't have time to maintain this project anymore so I'll archive it and add a note in the README. Feel free to fork it as you see fit.
